# Generated by Django 3.1.6 on 2021-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='imgdesc',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='imgtitle',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
