# Generated by Django 3.1.6 on 2021-05-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20210507_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='imgdesc',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='imgtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
