# Generated by Django 3.1.6 on 2021-05-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20210508_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='imgdesc',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='imgtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
