# Generated by Django 3.1.6 on 2021-05-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_auto_20210508_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='Images/'),
        ),
    ]
