# Generated by Django 3.1.6 on 2021-05-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
