# Generated by Django 3.1.6 on 2021-05-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Images/video')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
