# Generated by Django 3.2.3 on 2021-06-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0012_auto_20210603_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='imgdesc',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='imgtitle',
        ),
    ]
