# Generated by Django 3.1.6 on 2021-06-05 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0013_auto_20210603_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/vide/poster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
