# Generated by Django 3.1.6 on 2021-06-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0014_auto_20210605_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Poster',
        ),
    ]
