# Generated by Django 3.1.6 on 2021-06-05 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0015_remove_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/vide/poster'),
            preserve_default=False,
        ),
    ]
